spring:
  application:
    name: eos-cloud-config-api
  cloud:
    config:
      server:
        git:
          uri: /etc/eos-cloud-config-repo 

management:
  endpoints:
         web:
            exposure:
                 include: "health,info,prometheus"
  endpoint:
         health:
            show-details: always
  security:
    enabled: false
  metrics:
    export:
      prometheus:
        enabled: true

server:
  port: 8888

