spring:
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate.ddl-auto: create
    show-sql: true
    generate-ddl: false
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}
    group-id: ${KAFKA_GROUP_ID}

topic:
  name:
    producer: ${KAFKA_TOPIC_PRODUCER}
    consumer: ${KAFKA_TOPIC_CONSUMER}

cloud:
  azure:
    storage:
      account-name: ${AZURE_STORAGE_ACCOUNT_NAME}
      account-key: ${AZURE_STORAGE_ACCOUNT_KEY}

logging:
  level:
    com:
      azure:
        util:
          AzureCloudServiceStagingEnvironment: error

baseUrl: ${BASE_URL}

management:
  endpoints:
         web:
            exposure:
                 include: "health,info,prometheus"
  endpoint:
         health:
            show-details: always
  security:
    enabled: false
  metrics:
    export:
      prometheus:
        enabled: true

server:
  port: 8888

