server:
  port: 5555

management:
    endpoints:
         web:
            exposure:
                 include: "health,info,prometheus"
    endpoint:
         health:
              show-details: always
    metrics:
      export:
        prometheus:
          enabled: true
spring:
  application:
    name: eos-gateway-api
  cloud:
    gateway:
      routes:
        - id: eos-catalog-api-service
          uri: lb://eos-catalog-api-service
          predicates:
            - Path=/v1/catalog/**
        - id: eos-kart-api-service
          uri: lb://eos-kart-api-service
          predicates:
            - Path=/v1/kart/**
        - id: eos-payment-api-service
          uri: lb://eos-payment-api-service
          predicates:
            - Path=/v1/payment/**
        - id: eos-order-api-service
          uri: lb://eos-order-api-service
          predicates:
            - Path=/v1/order/**
        - id: eos-user-api
          uri: http://eos-user-api-service:8085/
          predicates:
            - Path=/v1/user/**
