server:
  port: 8083

spring:
  application:
    name: eos-kart-api-service
  cloud:
    kubernetes:
      config:
        name: default-name
        namespace: Default
        
management:
  endpoints:
        web:
          exposure:
                include: "health,info,prometheus"
  endpoint:
        health:
            show-details: always
  metrics:
    export:
      prometheus:
        enabled: true
  security:
    enabled: false
