server:
  port: 8084

spring:
  cloud:
    kubernetes:
      config:
        name: default-name
        namespace: Default

management:
  endpoints:
        web:
          exposure:
                include: "health,info,prometheus"
  endpoint:
        health:
            show-details: always
  metrics:
    export:
      prometheus:
        enabled: true
  security:
    enabled: false
